// Curated ecosystem registry. This is Nimglyde's core differentiator:
// users state intent, Nimglyde recommends a VERIFIED app + Open App action.
// Only list apps/resources you have actually verified. Add rows as you verify more.
export interface EcosystemApp {
  id: string;
  name: string;
  description: string;
  category: string;
  intents: string[]; // learn, play, send, payments, invoice, explore, build, save, stake
  openUrl: string; // live app, deeplink, or repo where the live URL is not yet verified
  sourceUrl: string; // docs / showcase / repo shown as source
  // false for official resources that are NOT Mini Apps: built-in wallets,
  // developer docs/tutorials, and program pages. They stay in the registry
  // so intent matching still finds them, but they are never counted or
  // listed as Mini Apps. Defaults to true when omitted.
  miniApp?: boolean;
}

export const ECOSYSTEM_APPS: EcosystemApp[] = [
  {
    id: "nimquest",
    name: "NimQuest",
    description: "Learn Nimiq by doing, then prove it with your own Nimiq wallet. Best first interactive app for newcomers.",
    category: "Education",
    intents: ["learn", "explore", "start"],
    openUrl: "https://github.com/mystiquemide/nimquest",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/mystiquemide",
  },
  {
    id: "nimjump",
    name: "NimJump",
    description: "Skill-based game with anti-cheat design. Good pick when users want to play a Nimiq game.",
    category: "Games",
    intents: ["play", "explore"],
    openUrl: "https://github.com/nimjump/game",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/emrealt34",
  },
  {
    id: "nimiq-space",
    name: "Nimiq Space",
    description: "Social-first multiplayer sandbox: build, create, earn. For exploring what people built on Nimiq.",
    category: "Social",
    intents: ["explore", "play"],
    openUrl: "https://github.com/harlski/nspace",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Harlski",
  },
  {
    id: "kashlink",
    name: "KashLink",
    description: "Send NIM to anyone with a link - no wallet address needed. Best answer for easy sending.",
    category: "Payments",
    intents: ["send", "payments"],
    openUrl: "https://github.com/crackedstudio/kashlink",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Otaiki1",
  },
  {
    id: "nim-invoice",
    name: "NIM Invoice",
    description: "Create a NIM invoice and get paid with a shareable link.",
    category: "Productivity",
    intents: ["invoice", "payments"],
    openUrl: "https://github.com/aloziephilemon5-dotcom/nim-invoice",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/aloziephilemon5-dotcom",
  },
  {
    id: "stash",
    name: "Stash",
    description: "Save when you spend, catch up when you miss. Savings with accountability.",
    category: "Finance",
    intents: ["save", "explore"],
    openUrl: "https://github.com/Emmanuel-webDev/Pay-Stash-Nimiq-",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Emmanuel-webDev",
  },
  {
    id: "bountyboard",
    name: "BountyBoard",
    description: "Get things done and get paid in NIM. Task bounties on Nimiq.",
    category: "Earning",
    intents: ["explore", "payments"],
    openUrl: "https://github.com/0andadream/Bounty-Board",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/0andadream",
  },
  {
    id: "nimchess",
    name: "NimChess",
    description: "Play chess, earn a NimRank, celebrate wins with NIM.",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/nftkingiii/nimchess",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/nftkingiii",
  },
  {
    id: "nimhunt",
    name: "NimHunt",
    description: "Create location spots, explore places, receive NIM rewards.",
    category: "Lifestyle",
    intents: ["explore", "play"],
    openUrl: "https://github.com/NIMHunt/nim-hunt",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/NIMHunt",
  },
  {
    id: "teach-it-back",
    name: "Teach It Back",
    description: "Master what you know by teaching it back. Learning through explaining.",
    category: "Education",
    intents: ["learn"],
    openUrl: "https://github.com/nimrid/Teach-It-Back",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/nimrid",
  },
  {
    id: "basepay",
    name: "BasePay",
    description: "The universal tip jar. Accept tips simply.",
    category: "Payments",
    intents: ["payments", "send"],
    openUrl: "https://github.com/xxcode66-source/basepay",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/xxcode66-source",
  },
  {
    id: "minirush",
    name: "MiniRush",
    description: "Arcade street racing inside Nimiq Pay with real NIM on the line.",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/Calebux/Mini-Rush",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Calebux",
  },
  {
    id: "pact",
    name: "Pact",
    description: "Don't just send money. Send certainty. Agreements backed by NIM.",
    category: "Payments",
    intents: ["send", "payments"],
    openUrl: "https://github.com/khaleed0019/pact",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/khaleed0019",
  },
  {
    id: "handback",
    name: "Handback",
    description: "Lend it, note it, get it back. Track lending between friends.",
    category: "Productivity",
    intents: ["explore", "payments"],
    openUrl: "https://github.com/ZackaryLoevseth/handback-nimiq",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/ZackaryLoevseth",
  },
  {
    id: "cinima",
    name: "Cinima",
    description: "Social taste discovery for movies and TV.",
    category: "Social",
    intents: ["explore", "play"],
    openUrl: "https://github.com/harlski/cinima",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Harlski",
  },
  {
    id: "nimiq-pay",
    name: "Nimiq Pay",
    description: "The wallet Mini Apps run inside. Use it to send NIM, approve payments, and open Mini Apps.",
    category: "Wallet",
    intents: ["send", "payments", "start", "wallet", "buy"],
    openUrl: "https://nimpay.app",
    sourceUrl: "https://nimiq.dev/mini-apps",
    miniApp: false,
  },
  {
    id: "wallet-nimiq",
    name: "Nimiq Wallet",
    description: "Create the Nimiq wallet that receives prize payouts and holds NIM.",
    category: "Wallet",
    intents: ["start", "wallet", "payments", "buy"],
    openUrl: "https://wallet.nimiq.com",
    sourceUrl: "https://wallet.nimiq.com",
    miniApp: false,
  },
  {
    id: "miniapp-docs",
    name: "Mini Apps Developer Docs",
    description: "Official tutorials, provider API reference, EVM token guide, testing and deployment.",
    category: "Developer",
    intents: ["build"],
    openUrl: "https://nimiq.dev/mini-apps",
    sourceUrl: "https://nimiq.dev/mini-apps",
    miniApp: false,
  },
  {
    id: "miniapp-tutorial",
    name: "Build Your First Mini App",
    description: "Step-by-step: account access, consensus checks, and block reads inside Nimiq Pay.",
    category: "Developer",
    intents: ["build"],
    openUrl: "https://nimiq.dev/mini-apps/tutorials/mini-app-tutorial",
    sourceUrl: "https://nimiq.dev/mini-apps/tutorials/mini-app-tutorial",
    miniApp: false,
  },
  {
    id: "dualchain-tutorial",
    name: "Dual-Chain Mini App Tutorial",
    description: "Nimiq + Ethereum providers together with confirmation flows.",
    category: "Developer",
    intents: ["build"],
    openUrl: "https://nimiq.dev/mini-apps/tutorials/dual-chain-mini-app-tutorial",
    sourceUrl: "https://nimiq.dev/mini-apps/tutorials/dual-chain-mini-app-tutorial",
    miniApp: false,
  },
  {
    id: "evm-tokens",
    name: "Using EVM Tokens (USDT on Polygon)",
    description: "Read balances and send ERC-20 transfers through window.ethereum. USDT uses 6 decimals.",
    category: "Developer",
    intents: ["build", "payments"],
    openUrl: "https://nimiq.dev/mini-apps/features/evm-tokens",
    sourceUrl: "https://nimiq.dev/mini-apps/features/evm-tokens",
    miniApp: false,
  },
  {
    id: "miniapp-ideas",
    name: "Mini App Ideas List",
    description: "Categorized build ideas with providers and external APIs for each.",
    category: "Developer",
    intents: ["build", "explore"],
    openUrl: "https://nimiq.dev/mini-apps/ideas",
    sourceUrl: "https://nimiq.dev/mini-apps/ideas",
    miniApp: false,
  },
  {
    id: "competition",
    name: "Mini Apps Competition",
    description: "Current cycle, rules, scoring, payout, submissions showcase.",
    category: "Ecosystem",
    intents: ["explore", "start"],
    openUrl: "https://miniappscompetition.com",
    sourceUrl: "https://miniappscompetition.com/rules",
    miniApp: false,
  },
  {
    id: "tiberius-ls-c1",
    name: "SteadyStreak",
    description: "Build habits. Save NIM safely. Stake only what you’ll risk.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/tiberius-ls/SteadyStreak",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/tiberius-ls",
  },
  {
    id: "iziedking-c1",
    name: "sFace",
    description: "Crypto is down. Somebody has to save face.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Iziedking/sFace",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Iziedking",
  },
  {
    id: "0xaje-c1",
    name: "NimiqFlow",
    description: "Smart Crypto Payments, Simplified.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/0xaje/-NimiqFlow-",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/0xaje",
  },
  {
    id: "birdcoin0-c1",
    name: "NimiFit",
    description: "Log meals, touch grass, earn NIM — wellness that pays you back.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/birdcoin0/nimifit-mini-app",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/birdcoin0",
  },
  {
    id: "sopskistar-c1",
    name: "EverRelay Mini",
    description: "Prepare your digital life before emergencies happen.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/sopskistar/everrelay",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/sopskistar",
  },
  {
    id: "yagami1610-c1",
    name: "Ajoo Savings",
    description: "Save to Earn",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/YAGAMI1610/Ajoo-savings",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/YAGAMI1610",
  },
  {
    id: "nazerbarkar-c1",
    name: "nimga",
    description: "Turn your dreams into images with your Nimiq wallet.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/nazerbarkar/nimga",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/nazerbarkar",
  },
  {
    id: "panoramicrum-c1",
    name: "Nimiq Radio",
    description: "One shared radio. Everyone hears the same song at the same moment.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/PanoramicRum/nimiq-radio",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/PanoramicRum",
  },
  {
    id: "nimhunt-c1",
    name: "NimHunt",
    description: "Create Spots. Explore Locations. Claim NIM.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/NIMHunt/nim-hunt",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/NIMHunt",
  },
  {
    id: "nailer-c1",
    name: "NIM Duel",
    description: "Tap. Stake. Win.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Nailer/nim-duel",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Nailer",
  },
  {
    id: "kehn-marv-c1",
    name: "Nimigora",
    description: "The Autonomous Newsroom",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Kehn-Marv/Nimigora",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Kehn-Marv",
  },
  {
    id: "kaelah971-c1",
    name: "Votum",
    description: "Your choice, verified",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/kaelah971/votum",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/kaelah971",
  },
  {
    id: "natureloved-c1",
    name: "TipWall",
    description: "Tip the creator, Not the platform.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/natureloved/TipWall",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/natureloved",
  },
  {
    id: "0xblaize-c1",
    name: "OpticPay",
    description: "Ai verify payment",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/0xblaize/OpticPay",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/0xblaize",
  },
  {
    id: "roadsidedev-c1",
    name: "Piggy",
    description: "Your onchain Piggy Bank  on NimiqPay",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/roadsidedev/piggy-nimq",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/roadsidedev",
  },
  {
    id: "timidan-c1",
    name: "NimDrops",
    description: "Send NIM.Earn NIM.  Share the moment.",
    category: "Payments",
    intents: ["payments", "send"],
    openUrl: "https://github.com/Timidan/nimdrops",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Timidan",
  },
  {
    id: "0xnexuz-c1",
    name: "Ergon",
    description: "Work On Proof",
    category: "Education",
    intents: ["learn"],
    openUrl: "https://github.com/0xNexuz/ergon",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/0xNexuz",
  },
  {
    id: "ashthunder-c1",
    name: "GatePass",
    description: "NIM tickets. Rotating QR. Door check-in that actually works.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/ashThunder/gatepass",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/AshThunder",
  },
  {
    id: "grimstroke1980-c1",
    name: "UnlockMedia",
    description: "Crypto pay-per-view for creators",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/grimstroke1980/unlockmedia",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/grimstroke1980",
  },
  {
    id: "yakiudoph-c1",
    name: "Vellum",
    description: "Explore history across epochs while processing seamless digital token payments.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/YakiUdoph/Vellum",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/YakiUdoph",
  },
  {
    id: "bsh54-c1",
    name: "Sesión",
    description: "Anyone can start a session near you. Others just join. Reserve your spot in NIM.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Bsh54/sesion",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Bsh54",
  },
  {
    id: "amexrip-c1",
    name: "SimplePGP",
    description: "Encrypted Messaging Platform",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/amexrip/SimplePGP",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/amexrip",
  },
  {
    id: "rbarais-c1",
    name: "PayShare",
    description: "Split the bill. Pay in crypto.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/rbarais/payshareminiapp",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/rbarais",
  },
  {
    id: "hiska-pj-c1",
    name: "Nimiq Invoice Pay",
    description: "Create invoices and get paid directly from your Nimiq wallet.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/hiska-pj/nimip",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/hiska-pj",
  },
  {
    id: "lvrojhan-c1",
    name: "NimiqStake",
    description: "Stake NIM, earn rewards, climb the leaderboard.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/lvrojhan/nimiqstake",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/lvrojhan",
  },
  {
    id: "harmssam-c1",
    name: "VeriLock",
    description: "Sign Free. Lock when it matters.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/harmssam/verilock",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/harmssam",
  },
  {
    id: "ajanaku1-c1",
    name: "Tanda",
    description: "Tanda coordinates a fixed rotating savings circle without holding its money.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/ajanaku1/Tanda",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/ajanaku1",
  },
  {
    id: "dorakingx-c1",
    name: "Roundtrip",
    description: "Split the trip. Settle in a tap.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/dorakingx/nimiq-roundtrip",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/dorakingx",
  },
  {
    id: "iniwura-c1",
    name: "Pull",
    description: "Post money, not products.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Iniwura/pull",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Iniwura",
  },
  {
    id: "dammygreene-c1",
    name: "Nimiq Pools",
    description: "Predict together. Settle with ease.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/dammygreene/NimiqPools",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/dammygreene",
  },
  {
    id: "somtiee-c1",
    name: "FLOWRIQ",
    description: "Automated recurring payments on Nimiq",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/Somtiee/FLOWRIQ",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Somtiee",
  },
  {
    id: "okeyamy-c1",
    name: "Kolo",
    description: "Your circle saves together. Nimiq makes it trustless.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/OkeyAmy/kolo",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/OkeyAmy",
  },
  {
    id: "lumacx-fcc-c1",
    name: "OtherMeApp",
    description: "One photo → your own AI character. Scenes, clips, live voice. First 5 free",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Lumacx-FCC/Nimiq-MiniApps",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Lumacx-FCC",
  },
  {
    id: "josueazc-c1",
    name: "NIMIQ-ARCADE",
    description: "Play and win",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/NIMIQ-MINIAPPS/NIMIQ-ARCADE",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/josueazc",
  },
  {
    id: "jaydearcadian-c1",
    name: "PactPay",
    description: "One outcome. Private contributions. Everyone settled in NIM.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/Jaydearcadian/pactpay-miniapp",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Jaydearcadian",
  },
  {
    id: "craxy220-prog-c1",
    name: "TrustPay",
    description: "Secure every transaction. Trust every deal.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/craxy220-prog/Trustpay-app",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/craxy220-prog",
  },
  {
    id: "imdavyking-c1",
    name: "Wallet quest",
    description: "You walk a character around a shared hub world where other players are visible in real time;",
    category: "Games",
    intents: ["learn", "play"],
    openUrl: "https://github.com/Imdavyking/wallet-quest",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Imdavyking",
  },
  {
    id: "louissarvin-c1",
    name: "Kado",
    description: "Gift a little money, drop a link. First to tap, first to claim — gasless, right inside Nimiq Pay.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/louissarvin/Kado",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/louissarvin",
  },
  {
    id: "maestroi-c1",
    name: "NimConnect",
    description: "Human-friendly crypto starts here.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/NimMiniApps/NimConnect",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/maestroi",
  },
  {
    id: "rudazy-c1",
    name: "Pact",
    description: "Money between friends, with weight.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/rudazy/Pact",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/rudazy",
  },
  {
    id: "mzterwalexzyy-c1",
    name: "Trove",
    description: "Funded bounties. Verified payouts.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/mzterwalexzyy/Trove",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/mzterwalexzyy",
  },
  {
    id: "gallareton-c1",
    name: "Nimble",
    description: "Pay anyone with a six-digit code.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/gallareton/nimble",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/gallareton",
  },
  {
    id: "opeyemimoses-c1",
    name: "NimBounty",
    description: "Outcome-based micro-task bounties on Nimiq Pay",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/OpeyemiMoses/NimBounty",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/OpeyemiMoses",
  },
  {
    id: "surfstyk-c1",
    name: "Stakes",
    description: "An app to quit quitting.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/surfstyk/stakes",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/surfstyk",
  },
  {
    id: "nimiqblue-c1",
    name: "Nimiq Bazar",
    description: "A persistent point-of-sale inventory for all your items. Stored locally in your device.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/NimiqBlue/nimiq-bazar/",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/NimiqBlue",
  },
  {
    id: "devacunetixtech-c1",
    name: "RallyNIM",
    description: "Rally your community. Reward every interaction.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/devacunetixtech/RallyNIM",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/devacunetixtech",
  },
  {
    id: "mayorken-c1",
    name: "Nim Dare",
    description: "Dare your friends. Prove it. Win NIM.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Mayorken/NIM-Dare",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Mayorken",
  },
  {
    id: "legendarytunzeverywhere-c1",
    name: "NimAgent",
    description: "Crypto as Easy as a Conversation.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/LegendaryTunzeverywhere/NimAgent",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/LegendaryTunzeverywhere",
  },
  {
    id: "18abhinav07-c1",
    name: "Pods",
    description: "Commit, Show-up, Earn Repeat. Make showing up feel real.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/18Abhinav07/Pods",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/18Abhinav07",
  },
  {
    id: "benraouanesoufiane-c1",
    name: "NimSub",
    description: "Create, discover, and subscribe to USDT-powered subscription plans on Polygon.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/benraouanesoufiane/NimSub",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/BenraouaneSoufiane",
  },
  {
    id: "fozagtx-c1",
    name: "Tab",
    description: "Split a restaurant bill into instant, feeless NIM payment requests with friends",
    category: "Education",
    intents: ["learn", "payments"],
    openUrl: "https://github.com/fozagtx/Tab",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/fozagtx",
  },
  {
    id: "nimrid-c1",
    name: "Bardtale Studio",
    description: "Create Storybooks, Custom Artworks & Witcher-Style Bardic Ballads",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/nimrid/Bardtale-AI",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/nimrid",
  },
  {
    id: "osamor19-c1",
    name: "Nimcapsule",
    description: "Lock a moment, Unlock a Gift",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/OSAMOR19/memoryvault.git",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/OSAMOR19",
  },
  {
    id: "sheen223-c1",
    name: "Renda Signal",
    description: "Make your message matter.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Sheen223/Renda-Signal",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Sheen223",
  },
  {
    id: "dropxpert-c1",
    name: "XcrowHub",
    description: "Create the deal. Protect the payment. Deliver with confidence.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/DropXpert/Xcrowhub",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/DropXpert",
  },
  {
    id: "0xkinno-c1",
    name: "Atelier",
    description: "Your digital storefront. One link. Instant NIM.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/0xkinno/atelier",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/0xkinno",
  },
  {
    id: "winsznx-c1",
    name: "Tally",
    description: "Top up once. Stop settling up.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/winsznx/tally",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/winsznx",
  },
  {
    id: "savage27z-c1",
    name: "Collect",
    description: "One link. Everyone chips in. No accounts, no fees, no chasing.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/Savage27z/Collect",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/Savage27z",
  },
  {
    id: "successaje-c1",
    name: "Rota",
    description: "Save together, get paid in turn -  no treasurer required",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/successaje/Rota",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle1/successaje",
  },
  {
    id: "nazerbarkar-c2",
    name: "NIMGA",
    description: "AI images and videos, powered by your Nimiq wallet.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/nazerbarkar/nimga",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/nazerbarkar",
  },
  {
    id: "levithefirst-c2",
    name: "Preventah",
    description: "It runs in the family. Don’t let it run you.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/levithefirst/preventah",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/levithefirst",
  },
  {
    id: "selfcrypto-c2",
    name: "Nimiq Names",
    description: "One name to pay them all on Nimiq",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/selfcrypto/nns",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/selfcrypto",
  },
  {
    id: "milliebanned-c2",
    name: "Agora",
    description: "Hire, collaborate, and get paid with confidence.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Milliebanned/agora",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Milliebanned",
  },
  {
    id: "surfstyk-c2",
    name: "Stakes",
    description: "Win your moment. Bank the day.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/surfstyk/stakes",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/surfstyk",
  },
  {
    id: "nifemi0-c2",
    name: "Minute Alibi",
    description: "Prove you were there. Sign the second. Keep the proof.",
    category: "Education",
    intents: ["learn"],
    openUrl: "https://github.com/Nifemi0/minute-alibi",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Nifemi0",
  },
  {
    id: "devshieldhq-c2",
    name: "BALLAST",
    description: "Turn a crash into parked yield, not panic.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/devshieldhq/Ballast",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/devshieldhq",
  },
  {
    id: "flockgg-c2",
    name: "Folester",
    description: "Social Media for Web3 on Mimiq",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/FlockGG/FolesterApp",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/FlockGG",
  },
  {
    id: "miao-yu-c2",
    name: "NimiqCafe",
    description: "Everything your NIM is doing, in one place.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/miao-yu/nimiq-cafe",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/miao-yu",
  },
  {
    id: "nicedaymiracle-c2",
    name: "NImstreak",
    description: "Small Steps. Real Stakes. A Better You.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/nicedaymiracle/nimstreak",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/nicedaymiracle",
  },
  {
    id: "pinnaclecryptng-c2",
    name: "PROVIA",
    description: "Check before you pay. Verify after you pay",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/PinnacleCryptNG/provia",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/PinnacleCryptNG",
  },
  {
    id: "big14way-c2",
    name: "NimStamp",
    description: "Loyalty stamp cards for any merchant, inside Nimiq Pay",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/big14way/nimstamp",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/big14way",
  },
  {
    id: "sniperchief-c2",
    name: "nimDay",
    description: "Your birthday. Your wishes. One beautiful link.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/sniperchief/NIMDAY",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/sniperchief",
  },
  {
    id: "ay0bhamii-c2",
    name: "OPERATOR",
    description: "Don't just play. Prove it.",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/Ay0bhamii/Operator",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Ay0bhamii",
  },
  {
    id: "sasam44-c2",
    name: "NimHouse",
    description: "7 skill games inside your Nimiq Pay wallet - free to play, no luck, no gambling.",
    category: "Games",
    intents: ["payments", "play"],
    openUrl: "https://github.com/sasam44/nimhouse",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/sasam44",
  },
  {
    id: "olamidepy-c2",
    name: "Dynamio",
    description: "Power in Motion",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Olamidepy/dynamio",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Olamidepy",
  },
  {
    id: "jamesvictor-o-c2",
    name: "Ralli",
    description: "Start something. Join something. Pass it on.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/JamesVictor-O/Ralli",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/JamesVictor-O",
  },
  {
    id: "phosterlabs-c2",
    name: "FixEstimate",
    description: "See it. Understand it. Estimate it.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/PhosterLabs/fixestimate-pay",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/PhosterLabs",
  },
  {
    id: "davieslennox0-c2",
    name: "Qorbit",
    description: "Trade real stocks, gift fractional shares, right inside Nimiq Pay.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/davieslennox0/qorbit-nimiq",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/davieslennox0",
  },
  {
    id: "saidur-droid-c2",
    name: "MergeEarn",
    description: "Fund issues. Reward merges.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Saidur-droid/MergeEarn",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Saidur-droid",
  },
  {
    id: "cipherencrypt-c2",
    name: "Drift",
    description: "Paper planes with NIM, inside Nimiq Pay.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/cipherEncrypt/Drift",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/cipherEncrypt",
  },
  {
    id: "obiajulu-gif-c2",
    name: "NimSeal",
    description: "Confidential invoices and protected payments, inside Nimiq Pay.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/Obiajulu-gif/nimseal",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Obiajulu-gif",
  },
  {
    id: "faadil1-c2",
    name: "NimCarry",
    description: "One NIM. One bridge at a time.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Faadil1/nimcarry",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Faadil1",
  },
  {
    id: "flamiinngo-c2",
    name: "Mimo",
    description: "The AI host that turns communities into live, participatory shows powered by Nimiq.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/playmimoapp/mimo",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/flamiinngo",
  },
  {
    id: "legendarytunzeverywhere-c2",
    name: "PROOF",
    description: "Learn it, Prove it, Earn it.",
    category: "Education",
    intents: ["learn"],
    openUrl: "https://github.com/LegendaryTunzeverywhere/PROOF",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/LegendaryTunzeverywhere",
  },
  {
    id: "sammy-xxiv-c2",
    name: "Nimtag",
    description: "Send NIM to a name, not an address",
    category: "Payments",
    intents: ["payments", "send"],
    openUrl: "https://github.com/sammy-XXIV/nimtag",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/sammy-XXIV",
  },
  {
    id: "kirstyjhawker-hms-c2",
    name: "Pay It Sideways",
    description: "Someone showed up for you. Show up for someone else.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/kirstyjhawker-hms/pay-it-sideways",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/kirstyjhawker-hms",
  },
  {
    id: "nim-z-c2",
    name: "NIMZ",
    description: "Survive the Horde. Earn NIM.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/nim-z/nimz",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/nim-z",
  },
  {
    id: "nimbil-c2",
    name: "Nimiq Billiards",
    description: "8-ball pool for NIM — play friends, beat AI, earn crypto",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/nimbil/nimiq-billiards",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/nimbil",
  },
  {
    id: "xcoder2088-c2",
    name: "QuickProof",
    description: "Snap it, prove it, send it.",
    category: "Education",
    intents: ["learn", "payments", "send"],
    openUrl: "https://github.com/xcoder2088/nimiq-quick-proof-tips-jar",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/xcoder2088",
  },
  {
    id: "natureloved-c2",
    name: "TipWall",
    description: "Tip the creator, Not the platform.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/natureloved/TipWall",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/natureloved",
  },
  {
    id: "mrnetwork0001-c2",
    name: "NimSnap",
    description: "Studio photos for ten cents a shot.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/mrnetwork0001/NimSnap",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/mrnetwork0001",
  },
  {
    id: "kaos-codm-c2",
    name: "NimCircle",
    description: "Shared savings goals powered by NIM.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/KAOS-CODM/nimcircle",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/KAOS-CODM",
  },
  {
    id: "profitandloss-c2",
    name: "BodyDouble",
    description: "\"Focus alongside someone, finish what you start.\"",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/profitandloss/bodydouble",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/profitandloss",
  },
  {
    id: "samuel1-ona-c2",
    name: "Terreno",
    description: "OWN THE WORLD, ONE PIXEL AT A TIME.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/crackedstudio/Terreno",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Samuel1-ona",
  },
  {
    id: "lilrobin4-c2",
    name: "NimMultiSend",
    description: "Pay everyone at once with NIM.",
    category: "Payments",
    intents: ["payments", "send"],
    openUrl: "https://github.com/lilrobin4/multisend",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/lilrobin4",
  },
  {
    id: "spagero763-c2",
    name: "Tandem",
    description: "One thumb. Two orbs. Sixty seconds.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Spagero763/tandem",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Spagero763",
  },
  {
    id: "shrooms08-c2",
    name: "nimcade",
    description: "Swipe. Play. Get paid.",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/shrooms08/nimcade",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/shrooms08",
  },
  {
    id: "eric-65-c2",
    name: "NimiqLearn",
    description: "Explain it back. And find the misconception you didn't know you had.",
    category: "Education",
    intents: ["learn"],
    openUrl: "https://github.com/Eric-65/nimiqlearn",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Eric-65",
  },
  {
    id: "kaichaosun-c2",
    name: "Knock",
    description: "Chat on Nimiq. For friends, family and community - not for spam.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/kaichaosun/knock-chat",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/kaichaosun",
  },
  {
    id: "oputasamuel-c2",
    name: "Savanna Run",
    description: "Run the path, Carry the story.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Oputasamuel/Savanna-Run",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Oputasamuel",
  },
  {
    id: "imprint-hash-c2",
    name: "Nimjar",
    description: "Staking made easy, right inside Nimiq Pay.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/imprint-hash/nimjar",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/imprint-hash",
  },
  {
    id: "patricetalon1-c2",
    name: "Polytico",
    description: "Trade the future with Nimiq micro-credits.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/patriceTalon1/polytico",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/patriceTalon1",
  },
  {
    id: "jr-kenny-c2",
    name: "Get  ransom",
    description: "Keep the light on for open work — NIM bounties on GitHub issues, paid on merge in Nimiq Pay",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/Jr-kenny/get-ransom",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Jr-kenny",
  },
  {
    id: "teevincscrypt-c2",
    name: "TeTe on Nimiq",
    description: "Challenge for stakes, or just play the arcade, skill decides both.",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/TeevincsCrypt/TeTe",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/TeevincsCrypt",
  },
  {
    id: "nimnft-c2",
    name: "Nimiq NFT Marketplace",
    description: "Discover, buy, and sell NFTs powered by Nimiq.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/nimnft/nimiq-nft-marketplace",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/nimnft",
  },
  {
    id: "mateojkk-c2",
    name: "asknim",
    description: "Your pocket AI, inside Nimiq Pay",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/mateojkk/AskNimi",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/mateojkk",
  },
  {
    id: "subimpact-c2",
    name: "NimBooks",
    description: "The books for your Nimiq wallet.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/subimpact/nimbooks",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/subimpact",
  },
  {
    id: "aremuibrahim2222-c2",
    name: "Nimiq deals",
    description: "Discover discounted products and pay with NIM through Nimiq Pay.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/Aremuibrahim2222/Nimiq-deals.git",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Aremuibrahim2222",
  },
  {
    id: "levilabs-hash-c2",
    name: "Nimiquette",
    description: "Payments with meaning.",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/levilabs-hash/nimiquette",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/levilabs-hash",
  },
  {
    id: "uyscuttyy-c2",
    name: "NimbTy",
    description: "Small tasks. Real pay. On Nimiq",
    category: "Payments",
    intents: ["payments"],
    openUrl: "https://github.com/uyscuttyy/NimbTy",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/uyscuttyy",
  },
  {
    id: "ogaremma-c2",
    name: "Veyronis",
    description: "Cross-chain escrow with evidence-backed dispute resolution.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Ogaremma/Veyronis",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Ogaremma",
  },
  {
    id: "teecash96-c2",
    name: "Cairn",
    description: "Map the idea before you build it.",
    category: "Mini App",
    intents: ["explore"],
    openUrl: "https://github.com/Teecash96/Cairn",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Teecash96",
  },
  {
    id: "aoki-non-c2",
    name: "Space Invaders",
    description: "Insert NIM. Blast Aliens. Own the High Score.",
    category: "Games",
    intents: ["play"],
    openUrl: "https://github.com/aoki-non/space-invader-nim",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/aoki-non",
  },
  {
    id: "zhiyilang074811-c2",
    name: "Nimiq TipJar",
    description: "Send micro-tips in NIM directly inside Nimiq Pay with one click.",
    category: "Payments",
    intents: ["payments", "send"],
    openUrl: "https://github.com/Zhiyilang074811/nimiq-tipjar",
    sourceUrl: "https://miniappscompetition.com/submissions/cycle2/Zhiyilang074811",
  },
];

const INTENT_KEYWORDS: Record<string, string[]> = {
  learn: ["learn", "new", "start", "beginner", "teach", "tutorial"],
  play: ["play", "game", "gaming", "fun", "race", "racing", "chess"],
  send: ["send", "transfer", "pay someone", "to alex", "kashlink", "send via link"],
  buy: ["buy", "buying", "purchase", "get nim", "where can i get", "exchange", "onramp", "on-ramp", "how to get nim", "where to get"],
  payments: ["payment", "payments", "checkout", "merchant", "accept", "tip"],
  invoice: ["invoice", "invoicing", "bill"],
  explore: ["explore", "built", "showcase", "discover", "apps", "ecosystem", "movie", "film"],
  build: ["build", "develop", "code", "mini app", "provider", "sdk", "api", "error", "connect wallet", "accept nim"],
  save: ["save", "savings", "goal", "stash"],
  stake: ["stake", "staking", "validator", "rewards"],
  wallet: ["balance", "wallet", "transaction", "nim do i have"],
  upgrade: ["pro", "super", "upgrade", "plan", "trial"],
};

export function detectIntent(message: string): string {
  const lower = message.toLowerCase();
  let best = "general";
  let bestScore = 0;
  for (const [intent, keywords] of Object.entries(INTENT_KEYWORDS)) {
    let score = 0;
    for (const kw of keywords) {
      // Whole-word/phrase match: bare "pro" must not fire on
      // "provide/process/proof", "play" on "display", "plan" on "explain".
      const esc = kw.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      if (new RegExp(`\\b${esc}\\b`, "i").test(lower)) score += kw.length;
    }
    if (score > bestScore) {
      bestScore = score;
      best = intent;
    }
  }
  return best;
}

export function isMiniApp(a: EcosystemApp): boolean {
  return a.miniApp !== false;
}

// Actual Mini Apps only (competition submissions). Docs, built-in wallets,
// and program pages are resources, never Mini Apps.
export const MINI_APPS: EcosystemApp[] = ECOSYSTEM_APPS.filter(isMiniApp);

export function isRepoUrl(url: string): boolean {
  return /github\.com/i.test(url);
}

export function actionLabelFor(app: EcosystemApp): string {
  return isRepoUrl(app.openUrl) ? "View source" : "Open App";
}

export function findAppsForIntent(intent: string, limit = 3): EcosystemApp[] {
  const direct = ECOSYSTEM_APPS.filter((a) => a.intents.includes(intent));
  // Do not pad with unrelated apps — return only direct matches.
  // Caller decides whether empty is okay (better than misleading game for wallet question).
  return direct.slice(0, limit);
}